In [1]:
# Write a function to compute 5/0 and use try/except to catch the exceptions.

try:
    i = 5/0
except:
    print('excption occured')

excption occured


In [24]:
# Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for s in subjects:
    for v in verbs:
        for o in objects:
            print(s,v,o)
    

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [59]:
# Write a function so that the columns of the output matrix are powers of the input vector.

import numpy as np

def func(lis):
    res = []
    lis1 = []
    for a in lis:
        for n in range(len(lis)):
            b = a**n
            lis1.append(b)
    res.append(lis1)   
    print(np.reshape(res, (len(lis),-1)))

lis = [1,2,3,4]
func(lis)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]
